server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: application
  static_configs:
  - targets:
      - "localhost"
    labels:
      job: goapp
      __path__: /var/log/app.log