global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "go-app"
    static_configs:
      - targets: ["app:8080"]
  - job_name: "envoy"
    metrics_path: /stats
    params:
        format: ['prometheus']
    static_configs:
      - targets: ["envoy:9901"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093" # This is the URL of your Alertmanager service

rule_files:
  - "/etc/prometheus/alert.rules.yml"
